version: '3'
services:
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - ./data/redis:/var/lib/redis
 
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        depends_on:
            - redis
        expose:
            - "5000"

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app
        ports:
            - "4000:4000"
